# Generated by Django 3.2.6 on 2021-08-26 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElegirRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Puntaje Total')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('dificultad', models.CharField(choices=[('Facil', 'Facil'), ('Normal', 'Normal'), ('Dificil', 'Dificil')], default='Facil', max_length=10)),
                ('categoria', models.CharField(choices=[('General', 'General'), ('Historia', 'Historia'), ('Geografia', 'Geografia'), ('Ciencia', 'Ciencia'), ('Deporte', 'Deporte'), ('Arte', 'Arte'), ('Entretenimiento', 'Entretenimiento')], default='General', max_length=15)),
                ('max_puntaje', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Maximo Puntaje')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasRespondidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Es esta la respuesta correcta?')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Puntaje Obtenido')),
                ('participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='aplicacion.participante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.pregunta')),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.elegirrespuesta')),
            ],
        ),
        migrations.AddField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='aplicacion.pregunta'),
        ),
    ]
