# Generated by Django 3.2 on 2021-09-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_elegirrespuesta_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('General', 'General'), ('Historia', 'Historia'), ('sdads', 'Geografia'), ('Ciencia', 'Ciencia'), ('Deporte', 'Deporte'), ('Arte', 'Arte'), ('Entretenimiento', 'Entretenimiento')], default='General', max_length=15),
        ),
    ]
